language: java
env:
  - ACTIVATOR_VERSION=1.1.3 \
    ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip \
    ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE} \
    ACTIVATOR_BIN=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal/activator
install:
  - wget ${ACTIVATOR_ZIP_URL}
  - unzip -q ${ACTIVATOR_ZIP_FILE}
script:
  - "cd $TRAVIS_BUILD_DIR/code && ${ACTIVATOR_BIN} test publish-local"
  - "cd $TRAVIS_BUILD_DIR/test-app ${ACTIVATOR_BIN} test"
  - "cd $TRAVIS_BUILD_DIR/samples/java/play-authenticate-usage && ${ACTIVATOR_BIN} test"
  - "cd $TRAVIS_BUILD_DIR/play-authenticate-simple-oauth && ${ACTIVATOR_BIN} test"
notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false
